---
name: Run Tests
on: push

jobs:
  build:
    name: Run tests on
    runs-on: ubuntu-latest

    container:
      image: golang:alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: apk add make

      - name: Run tests
        run: make test
