---
name: Run Tests
on: push

jobs:
  build:
    name: Run tests on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]

    container:
      image: golang:alpine
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: apk add make

      - name: Run tests
        run: make test
